/** Bounded Node observations for closures, timers, state machines and concurrency. */
import type{TestDetail}from'@zxbench/types';import{runInContainer,CONTAINER_IMAGES,type ContainerRunOptions}from'./containerRunner.js';import{validObservationJson}from'./quickJsObservation.js';import{validJsonValuePredicate,matchesJsonValuePredicate,type JsonValuePredicate}from'./jsonValuePredicate.js';import type{JsonValue}from'./isolatedJson.js';
export type JavascriptJsonAdapter='counters'|'retry'|'bus'|'debounce'|'lru'|'promise-limit'|'fib'|'agent-run'|'call-budget'|'set-deep'|'bank'|'query-string'|'fetch-retry';export interface IsolatedJavascriptJsonCase{id:string;calls:JsonValue[][];expected:JsonValuePredicate[]}export interface IsolatedJavascriptJsonContract{protocol:'isolated-javascript-json-v1';entrypoint:string;adapter:JavascriptJsonAdapter;cases:IsolatedJavascriptJsonCase[]}
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
export function validIsolatedJavascriptJsonContract(v:unknown):v is IsolatedJavascriptJsonContract{if(!rec(v)||v.protocol!=='isolated-javascript-json-v1'||!['counters','retry','bus','debounce','lru','promise-limit','fib','agent-run','call-budget','set-deep','bank','query-string','fetch-retry'].includes(v.adapter as string)||typeof v.entrypoint!=='string'||!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v.entrypoint)||!Array.isArray(v.cases)||!v.cases.length||v.cases.length>20)return false;const ids=new Set<string>();return v.cases.every((c:unknown)=>rec(c)&&typeof c.id==='string'&&!ids.has(c.id)&&!!ids.add(c.id)&&Array.isArray(c.calls)&&c.calls.length>0&&c.calls.length<=20&&c.calls.every((x:unknown)=>Array.isArray(x)&&validObservationJson(x)&&Buffer.byteLength(JSON.stringify(x))<65536)&&Array.isArray(c.expected)&&c.expected.length===c.calls.length&&validObservationJson(c.expected)&&c.expected.every(validJsonValuePredicate));}
const driver=`import{readFileSync}from'node:fs';const write=process.stdout.write.bind(process.stdout),req=JSON.parse(readFileSync('/workspace/input.json','utf8'));console.log=console.info=console.warn=(...x)=>console.error(...x);const mod=await import('./candidate.mjs'),E=mod.zxEntry,S=mod.zxSecondary;const sleep=ms=>new Promise(r=>setTimeout(r,ms)),out=[];
for(const c of req.calls){const a=req.adapter;
 if(a==='counters'){const f=E(c[0]);out.push(c[1]==='all'?f.map(x=>x()):c[2].map(i=>f[i]()));}
 else if(a==='retry'){let n=0;try{const v=E(()=>{n++;if(n<c[0])throw Error('e'+n);return c[2]},c[1]);out.push({kind:'return',value:v,calls:n})}catch(e){out.push({kind:'throw',message:e?.message,calls:n})}}
 else if(a==='bus'){const b=new E();if(c[0]==='off'){let n=0;const f=()=>n++;b.on('e',f);b.emit('e');b.off('e',f);b.emit('e');out.push(n)}else if(c[0]==='selective'){let x=0,y=0;const f=()=>x++,g=()=>y++;b.on('e',f);b.on('e',g);b.off('e',f);b.emit('e');out.push([x,y])}else{let x=0,y=0;const g=()=>y++,f=()=>{x++;b.off('e',g)};b.on('e',f);b.on('e',g);b.emit('e');b.emit('none');out.push([x,y])}}
 else if(a==='debounce'){if(c[0]==='burst'){const calls=[],d=E(x=>calls.push(x),20);d(1);d(2);d(3);await sleep(45);out.push(calls)}else if(c[0]==='early'){const calls=[],d=E(x=>calls.push(x),30);d('a');await sleep(10);const early=calls.length;await sleep(40);out.push([early,calls])}else{const o={sum:0},d=E(function(x,y){this.sum+=x+y},20);d.call(o,1,2);d.call(o,3,4);await sleep(45);out.push(o.sum)}}
 else if(a==='lru'){const x=new E(2);if(c[0]==='get'){x.put(1,1);x.put(2,2);out.push(x.get(1))}else if(c[0]==='evict'){x.put(1,1);x.put(2,2);x.put(3,3);out.push([x.get(1),x.get(3)])}else{x.put(1,1);x.put(2,2);x.get(1);x.put(3,3);out.push([x.get(2),x.get(1)])}}
 else if(a==='promise-limit'){if(c[0]==='values'){const vs=c[1],tasks=vs.map(v=>()=>new Promise(r=>setTimeout(()=>r(v*v),5)));out.push(await E(tasks,c[2]))}else if(c[0]==='concurrency'){let active=0,max=0,calls=0;const tasks=Array.from({length:c[1]},(_,i)=>()=>new Promise(r=>{calls++;active++;max=Math.max(max,active);setTimeout(()=>{active--;r(i)},10)}));out.push([await E(tasks,c[2]),calls,max])}else out.push([await E([],2),await E([()=>Promise.resolve('a'),()=>Promise.resolve('b')],1)])}
 else if(a==='agent-run'){if(c[0]==='happy')out.push(E([{tool:'a',args:1},{tool:'b',args:2}],{a:x=>x+1,b:x=>x*2}));else if(c[0]==='error')out.push(E([{tool:'a',args:1},{tool:'b',args:2}],{a:x=>x,b:()=>{throw Error('boom')}}));else out.push(E([],{}))}
 else if(a==='call-budget'){let n=0;try{const v=E(()=>{n++;if(n<c[0])throw Error(c[3]);return c[4]},{maxRetries:c[1],maxCalls:c[2]});out.push({kind:'return',value:v,calls:n})}catch(e){out.push({kind:'throw',message:e?.message,calls:n})}}
 else if(a==='set-deep'){if(c[0]==='normal'){const o={a:{keep:1}};E(o,'a.b.c',42);out.push(o)}else{const o={},key=c[1];try{E(o,c[2],c[3])}catch{}const clean=({})[key]===undefined;delete Object.prototype[key];out.push(clean)}}
 else if(a==='bank'){const b=new E();if(c[0]==='missing'){b.createAccount('a',100);let threw=false;try{b.transfer('a','ghost',30)}catch{threw=true}out.push([threw,b.getBalance('a')])}else{b.createAccount('a',50);b.createAccount('b',0);let threw=false;try{b.transfer('a','b',1000)}catch{threw=true}b.transfer('a','b',20);out.push([threw,b.getBalance('a'),b.getBalance('b')])}}
 else if(a==='query-string'){if(c[0]==='parse'){const p1=E('q=hello+world'),p2=E('a=1&a=2'),p3=E('flag'),p4=E('k='),p5=E('u=a=b');out.push([p1.q,p2.a,p3.flag,Object.prototype.hasOwnProperty.call(p4,'k'),p4.k,p5.u])}else{const p=E('n=%E5%BC%A0%E4%B8%89&x=%20');out.push([p.n,p.x,S({q:'a b&c',u:null,v:undefined})])}}
 else if(a==='fetch-retry'){if(c[0]==='client'){let n=0;globalThis.fetch=async()=>{n++;return{ok:false,status:404}};let threw=false;try{await E('/x',{maxRetries:3,baseDelay:0})}catch{threw=true}out.push([threw,n])}else{let n=0;globalThis.fetch=async()=>{n++;return n<3?{ok:false,status:500}:{ok:true,json:async()=>({success:true})}};const r=await E('/x',{maxRetries:3,baseDelay:0}),successCalls=n;n=0;globalThis.fetch=async()=>{n++;return{ok:false,status:503}};let threw=false;try{await E('/x',{maxRetries:2,baseDelay:0})}catch{threw=true}out.push([r.success,successCalls,threw,n])}}
 else if(a==='fib'){const start=performance.now(),values=c[0].map(n=>E(n));out.push([values,performance.now()-start<c[1]])}}
write(JSON.stringify(out));`;
export function isolatedJavascriptOptions(code:string,c:IsolatedJavascriptJsonContract,calls:JsonValue[][],compileOnly=false):ContainerRunOptions{if(!validIsolatedJavascriptJsonContract({...c,cases:[{id:'input',calls,expected:calls.map(()=>({equals:null}))}]}))throw Error('Invalid JavaScript observation input');const source=code+(c.adapter==='query-string'?'\nexport { parseQueryString as zxEntry, buildQueryString as zxSecondary };\n':'\nexport { '+c.entrypoint+' as zxEntry };\n');return{image:CONTAINER_IMAGES.javascript,command:compileOnly?['node','--check','candidate.mjs']:['node','driver.mjs'],files:compileOnly?[{path:'candidate.mjs',content:source}]:[{path:'candidate.mjs',content:source},{path:'driver.mjs',content:driver},{path:'input.json',content:JSON.stringify({adapter:c.adapter,calls})}],localImageOnly:true,readOnlyRoot:true,readOnly:true,networkDisabled:true,runAsNonRoot:true,memoryMb:128,cpuLimit:1,pidsLimit:32,timeoutMs:c.adapter==='fib'?4000:8000,maxOutputBytes:65536,env:{HOME:'/tmp'}};}
export async function runIsolatedJavascriptJsonSuite(code:string,c:IsolatedJavascriptJsonContract){if(!validIsolatedJavascriptJsonContract(c))throw Error('Invalid JavaScript observation contract');const syntax=await runInContainer(isolatedJavascriptOptions(code,c,c.cases[0].calls,true));let infrastructureError=syntax.infrastructureError;const details:TestDetail[]=[];for(const k of c.cases){if(infrastructureError)break;const startedAt=new Date().toISOString(),r=syntax.success?await runInContainer(isolatedJavascriptOptions(code,c,k.calls)):syntax;infrastructureError=r.infrastructureError;let passed=false;if(r.success&&!r.timedOut&&!r.outputLimitExceeded&&!r.infrastructureError)try{const v:unknown=JSON.parse(r.stdout);passed=Array.isArray(v)&&v.length===k.expected.length&&validObservationJson(v)&&k.expected.every((p,i)=>matchesJsonValuePredicate(v[i],p));}catch{}details.push({testId:k.id,testType:'hidden',passed,stdout:r.stdout,stderr:r.stderr,actualOutput:r.stdout,exitCode:r.exitCode,timedOut:r.timedOut,duration:r.durationMs,startedAt,finishedAt:new Date().toISOString()});}return{compiled:syntax.success,compileError:syntax.success?undefined:syntax.stderr,infrastructureError,details,total:c.cases.length,passed:details.filter(x=>x.passed).length};}
