/** Language-specific container assertions with a host-owned final verdict. */
import type { HiddenTestCase, TestDetail } from '@zxbench/types';
import { runCTestsInContainer, runCppTestsInContainer, runCppTreiberStressInContainer, type CFixture } from './cRunner.js';
import { runRustTestsInContainer, runRustMiriInContainer, type RustFixture } from './rustRunner.js';
import { runBashTestsInContainer, type BashFixture } from './bashRunner.js';
import { runTestCaseInContainer, runReplacedCodeTestPythonInContainer } from '../sandbox/index.js';
import { envErrorOf } from '../evaluators/harnessErrors.js';
export type FixtureLanguage='c'|'cpp'|'rust'|'bash'|'javascript'|'python';
export interface IsolatedFixtureExitContract{protocol:'isolated-fixture-exit-v1';entrypoint:string;language:FixtureLanguage;mode:'cases'|'tsan'|'miri';caseIds:string[]}
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
export function validIsolatedFixtureExitContract(v:unknown):v is IsolatedFixtureExitContract{if(!rec(v)||v.protocol!=='isolated-fixture-exit-v1'||typeof v.entrypoint!=='string'||!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v.entrypoint)||!['c','cpp','rust','bash','javascript','python'].includes(v.language as string)||!['cases','tsan','miri'].includes(v.mode as string)||!Array.isArray(v.caseIds)||!v.caseIds.length||v.caseIds.length>20)return false;return new Set(v.caseIds).size===v.caseIds.length&&v.caseIds.every(x=>typeof x==='string'&&x.length>0&&x.length<120)}
const summary=(details:TestDetail[],compiled:boolean,compileError?:string,infrastructureError?:string)=>({compiled,compileError,infrastructureError,details,total:details.length,passed:details.filter(x=>x.passed).length});
export async function runIsolatedFixtureExitSuite(code:string,contract:IsolatedFixtureExitContract,tests:HiddenTestCase[],fixture:unknown,flags:{forbidMutex?:boolean;forbidTransmute?:boolean}={}){
 if(!validIsolatedFixtureExitContract(contract))throw Error('Invalid fixture exit contract');
 if(contract.mode==='tsan'){const r=await runCppTreiberStressInContainer(code,120000),env=envErrorOf(r),orders=/head_\.load\s*\(\s*std::memory_order_acquire\s*\)/s.test(code)&&/compare_exchange_weak\s*\([^;]*std::memory_order_acquire\s*,\s*std::memory_order_relaxed/s.test(code);if(env.isEnv)return summary([],false,undefined,env.reason);const details:TestDetail[]=[{testId:contract.caseIds[0],testType:'static',passed:orders,timedOut:false},{testId:contract.caseIds[1],testType:'hidden',passed:r.passed,timedOut:r.timedOut},{testId:contract.caseIds[2],testType:'static',passed:!flags.forbidMutex||!/std::mutex|lock_guard|unique_lock|scoped_lock|pthread_mutex/.test(code),timedOut:false}];return summary(details,!r.compileError,r.stderr)}
 if(contract.mode==='miri'){const r=await runRustMiriInContainer(code,180000),env=envErrorOf(r),ok=r.miriClean&&r.testsPassed===r.testsTotal;if(env.isEnv)return summary([],false,undefined,env.reason);const details:TestDetail[]=contract.caseIds.map((id,i)=>({testId:id,testType:i===contract.caseIds.length-1?'static':'hidden',passed:i===contract.caseIds.length-1?(!flags.forbidTransmute||!/\btransmute\b/.test(code)):ok,timedOut:r.timedOut}));return summary(details,r.compiled,r.stderr)}
 if(tests.length!==contract.caseIds.length||tests.some((t,i)=>t.id!==contract.caseIds[i]))throw Error('Fixture case IDs do not match');
 if(contract.language==='javascript'||contract.language==='python'){const details=await Promise.all(tests.map(t=>contract.language==='python'?runReplacedCodeTestPythonInContainer(code,t):runTestCaseInContainer(code,null,t))),env=envErrorOf({stderr:details.map(d=>d.stderr??'').join('\n')});if(env.isEnv)return summary([],false,undefined,env.reason);return summary(details,details.every(d=>!/SyntaxError/.test(d.stderr??'')),details.find(d=>/SyntaxError/.test(d.stderr??''))?.stderr)}
 const r=contract.language==='c'?await runCTestsInContainer(code,tests,fixture as CFixture,8000):contract.language==='cpp'?await runCppTestsInContainer(code,tests,fixture as CFixture,8000):contract.language==='rust'?await runRustTestsInContainer(code,tests,fixture as RustFixture,8000):await runBashTestsInContainer(code,tests,fixture as BashFixture,15000);
 const env=envErrorOf(r);if(env.isEnv)return summary([],false,undefined,env.reason);const details:TestDetail[]=r.tests.map((x,i)=>({testId:contract.caseIds[i],testType:'hidden',passed:x.passed,timedOut:r.timedOut,stderr:x.passed?'':'assertion or completion check failed'}));return summary(details,r.compiled,r.stderr);
}
