/** Bounded SQLite query observations with host-owned result and plan predicates. */
import type{TestDetail}from'@zxbench/types';
import{runInContainer,type ContainerRunOptions}from'./containerRunner.js';
import{validObservationJson}from'./quickJsObservation.js';
import{matchesJsonValuePredicate,validJsonValuePredicate,type JsonValuePredicate}from'./jsonValuePredicate.js';
export interface IsolatedSqlJsonCase{id:string;schema:string;seed:string;expected:JsonValuePredicate;forbidPlan?:string[];requirePlan?:string[]}
export interface IsolatedSqlJsonContract{protocol:'isolated-sql-json-v1';entrypoint:'query';cases:IsolatedSqlJsonCase[]}
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
export function validIsolatedSqlJsonContract(v:unknown):v is IsolatedSqlJsonContract{if(!rec(v)||v.protocol!=='isolated-sql-json-v1'||v.entrypoint!=='query'||!Array.isArray(v.cases)||!v.cases.length||v.cases.length>20)return false;const ids=new Set<string>();return v.cases.every((c:unknown)=>rec(c)&&typeof c.id==='string'&&!ids.has(c.id)&&!!ids.add(c.id)&&typeof c.schema==='string'&&typeof c.seed==='string'&&Buffer.byteLength(c.schema+c.seed)<131072&&validObservationJson(c.expected)&&validJsonValuePredicate(c.expected)&&(!c.forbidPlan||Array.isArray(c.forbidPlan)&&c.forbidPlan.every((x:unknown)=>typeof x==='string'&&x.length<200))&&(!c.requirePlan||Array.isArray(c.requirePlan)&&c.requirePlan.every((x:unknown)=>typeof x==='string'&&x.length<200)));}
const driver=`import{DatabaseSync}from'node:sqlite';import{readFileSync}from'node:fs';const input=JSON.parse(readFileSync('/workspace/input.json','utf8')),query=readFileSync('/workspace/query.sql','utf8'),db=new DatabaseSync(':memory:');db.exec(input.schema+'\\n'+input.seed);const rows=db.prepare(query).all(),plan=db.prepare('EXPLAIN QUERY PLAN '+query).all().map(x=>x.detail).join('\\n');process.stdout.write(JSON.stringify({rows,plan}));`;
export function isolatedSqlOptions(query:string,c:IsolatedSqlJsonCase):ContainerRunOptions{return{image:'node:22-alpine',command:['node','driver.mjs'],files:[{path:'query.sql',content:query},{path:'driver.mjs',content:driver},{path:'input.json',content:JSON.stringify({schema:c.schema,seed:c.seed})}],localImageOnly:true,readOnlyRoot:true,readOnly:true,networkDisabled:true,runAsNonRoot:true,memoryMb:192,cpuLimit:1,pidsLimit:32,timeoutMs:3000,maxOutputBytes:131072,env:{HOME:'/tmp'}};}
export async function runIsolatedSqlJsonSuite(query:string,c:IsolatedSqlJsonContract){if(!validIsolatedSqlJsonContract(c))throw Error('Invalid SQL observation contract');let infrastructureError:string|undefined;const details:TestDetail[]=[];let compiled=true;let compileError:string|undefined;for(const k of c.cases){if(infrastructureError)break;const startedAt=new Date().toISOString(),r=await runInContainer(isolatedSqlOptions(query,k));infrastructureError=r.infrastructureError;let passed=false;if(r.success&&!r.timedOut&&!r.outputLimitExceeded&&!r.infrastructureError)try{const v=JSON.parse(r.stdout);const plan=typeof v?.plan==='string'?v.plan:'';passed=validObservationJson(v?.rows)&&matchesJsonValuePredicate(v.rows,k.expected)&&(k.forbidPlan??[]).every(x=>!plan.toLowerCase().includes(x.toLowerCase()))&&(k.requirePlan??[]).every(x=>plan.toLowerCase().includes(x.toLowerCase()));}catch{}else if(!r.infrastructureError){compiled=false;compileError??=r.stderr}details.push({testId:k.id,testType:'hidden',passed,stdout:r.stdout,stderr:r.stderr,actualOutput:r.stdout,exitCode:r.exitCode,timedOut:r.timedOut,duration:r.durationMs,startedAt,finishedAt:new Date().toISOString()});}return{compiled,compileError,infrastructureError,details,total:c.cases.length,passed:details.filter(x=>x.passed).length};}
