/** Runtime observations for erasable TypeScript in a bounded Node 22 container. */
import type{TestDetail}from'@zxbench/types';
import{runInContainer,type ContainerRunOptions}from'./containerRunner.js';
import{validObservationJson}from'./quickJsObservation.js';
import{validJsonValuePredicate,matchesJsonValuePredicate,type JsonValuePredicate}from'./jsonValuePredicate.js';
import type{JsonValue}from'./isolatedJson.js';
export type TypescriptJsonAdapter='area'|'page-items'|'api-result';
export interface IsolatedTypescriptJsonCase{id:string;calls:JsonValue[][];expected:JsonValuePredicate[]}
export interface IsolatedTypescriptJsonContract{protocol:'isolated-typescript-json-v1';entrypoint:string;adapter:TypescriptJsonAdapter;cases:IsolatedTypescriptJsonCase[]}
const rec=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
export function validIsolatedTypescriptJsonContract(v:unknown):v is IsolatedTypescriptJsonContract{if(!rec(v)||v.protocol!=='isolated-typescript-json-v1'||!['area','page-items','api-result'].includes(v.adapter as string)||typeof v.entrypoint!=='string'||!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v.entrypoint)||!Array.isArray(v.cases)||!v.cases.length||v.cases.length>20)return false;const ids=new Set<string>();return v.cases.every((c:unknown)=>rec(c)&&typeof c.id==='string'&&!ids.has(c.id)&&!!ids.add(c.id)&&Array.isArray(c.calls)&&c.calls.length>0&&c.calls.length<=20&&c.calls.every((x:unknown)=>Array.isArray(x)&&validObservationJson(x))&&Array.isArray(c.expected)&&c.expected.length===c.calls.length&&validObservationJson(c.expected)&&c.expected.every(validJsonValuePredicate));}
const driver=`import{readFileSync}from'node:fs';const req=JSON.parse(readFileSync('/workspace/input.json','utf8')),m=await import('./candidate.ts'),out=[];for(const c of req.calls){if(req.adapter==='area')out.push(m.area(c[0]));else if(req.adapter==='page-items'){if(c[0]==='lazy'){let calls=0;const pages=[{items:[1,2],cursor:'c1'},{items:[3],cursor:null}],fetch=async x=>(calls++,x===null?pages[0]:pages[1]),g=m.pageItems(fetch),first=await g.next();out.push([first.done,first.value,calls])}else if(c[0]==='collect'){let calls=0;const pages=[{items:['a','b'],cursor:'c1'},{items:['c'],cursor:'c2'},{items:['d','e'],cursor:null}],fetch=async x=>(calls++,x===null?pages[0]:x==='c1'?pages[1]:pages[2]),values=[];for await(const x of m.pageItems(fetch))values.push(x);out.push([values,calls])}else if(c[0]==='empty-page'){const pages=[{items:[1],cursor:'c1'},{items:[],cursor:'c2'},{items:[2],cursor:null}],fetch=async x=>x===null?pages[0]:x==='c1'?pages[1]:pages[2],values=[];for await(const x of m.pageItems(fetch))values.push(x);out.push(values)}else{let calls=0,first,kind='return',message='';const fetch=async x=>{calls++;if(x===null)return{items:[1],cursor:'c1'};throw Error('boom')},g=m.pageItems(fetch);first=await g.next();try{await g.next()}catch(e){kind='throw';message=e?.message}out.push([first.value,kind,message,calls])}}else{let failure='return';try{m.unwrap({ok:false,error:'boom'})}catch(e){failure=e?.message}let never='return';try{m.assertNever('x')}catch(e){never=e?.message}out.push([failure,[200,404,500].map(m.handleStatus),never])}}process.stdout.write(JSON.stringify(out));`;
export function isolatedTypescriptOptions(code:string,c:IsolatedTypescriptJsonContract,calls:JsonValue[][]):ContainerRunOptions{if(!validIsolatedTypescriptJsonContract({...c,cases:[{id:'input',calls,expected:calls.map(()=>({equals:null}))}]}))throw Error('Invalid TypeScript observation input');const names=c.adapter==='api-result'?'unwrap,assertNever,handleStatus':c.entrypoint,source=code.replace(/\bexport\s+(?=(?:async\s+)?function|class|type|interface)/g,'');return{image:'node:22-alpine',command:['node','--experimental-strip-types','driver.mjs'],files:[{path:'candidate.ts',content:source+`\nexport {${names}};\n`},{path:'driver.mjs',content:driver},{path:'input.json',content:JSON.stringify({adapter:c.adapter,calls})}],localImageOnly:true,readOnlyRoot:true,readOnly:true,networkDisabled:true,runAsNonRoot:true,memoryMb:160,cpuLimit:1,pidsLimit:32,timeoutMs:8000,maxOutputBytes:65536,env:{HOME:'/tmp'}};}
export async function runIsolatedTypescriptJsonSuite(code:string,c:IsolatedTypescriptJsonContract){if(!validIsolatedTypescriptJsonContract(c))throw Error('Invalid TypeScript observation contract');let infrastructureError:string|undefined;const details:TestDetail[]=[];let compiled=true;let compileError:string|undefined;for(const k of c.cases){if(infrastructureError)break;const startedAt=new Date().toISOString(),r=await runInContainer(isolatedTypescriptOptions(code,c,k.calls));infrastructureError=r.infrastructureError;let passed=false;if(r.success&&!r.timedOut&&!r.outputLimitExceeded&&!r.infrastructureError)try{const v:unknown=JSON.parse(r.stdout);passed=Array.isArray(v)&&v.length===k.expected.length&&validObservationJson(v)&&k.expected.every((p,i)=>matchesJsonValuePredicate(v[i],p));}catch{}else if(!r.infrastructureError){compiled=false;compileError??=r.stderr}details.push({testId:k.id,testType:'hidden',passed,stdout:r.stdout,stderr:r.stderr,actualOutput:r.stdout,exitCode:r.exitCode,timedOut:r.timedOut,duration:r.durationMs,startedAt,finishedAt:new Date().toISOString()});}return{compiled,compileError,infrastructureError,details,total:c.cases.length,passed:details.filter(x=>x.passed).length};}
