import type{IsolatedPythonJsonContract}from'../execution/isolatedPythonJson.js';
import{ISOLATED_PYTHON_JSON_V2_PILOTS}from'./isolatedPythonJsonV2Gold.js';
export interface IsolatedPythonJsonFixture{language:'python';contract:IsolatedPythonJsonContract;correct:string;mutant:string;developmentCases:IsolatedPythonJsonContract['cases']}
const eq=(equals:any)=>({equals});
export const ISOLATED_PYTHON_JSON_PILOTS:Record<string,IsolatedPythonJsonFixture>={...ISOLATED_PYTHON_JSON_V2_PILOTS,
'CP-L1-PY-001':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'add_item',adapter:'mutable-default',cases:[{id:'CP-L1-PY-001-hidden-1',calls:[['one',1]],expected:[eq([1])]},{id:'CP-L1-PY-001-hidden-2',calls:[['pollution',1,2]],expected:[eq([2])]},{id:'CP-L1-PY-001-hidden-3',calls:[['identity',9]],expected:[eq(true)]}]},correct:'def add_item(item, cart=None):\n    if cart is None: cart=[]\n    cart.append(item)\n    return cart',mutant:'def add_item(item, cart=[]):\n    cart.append(item)\n    return list(cart)',developmentCases:[{id:'DEV-PY-ADD-negative',calls:[['pollution',-1,-2]],expected:[eq([-2])]}]},
'CP-L1-PY-003':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'group_by',adapter:'group-by',cases:[{id:'CP-L1-PY-003-hidden-1',calls:[['mod2',[1,2,3,4]]],expected:[eq({'1':[1,3],'0':[2,4]})]},{id:'CP-L1-PY-003-hidden-2',calls:[['identity',[]]],expected:[eq({})]},{id:'CP-L1-PY-003-hidden-3',calls:[['len',['ab','cd','e']]],expected:[eq({'2':['ab','cd'],'1':['e']})]}]},correct:'def group_by(items,key_fn):\n    out={}\n    for item in items: out.setdefault(key_fn(item),[]).append(item)\n    return out',mutant:'def group_by(items,key_fn):\n    return {key_fn(x):[x] for x in items}',developmentCases:[{id:'DEV-PY-GROUP-repeat',calls:[['len',['a','b','cc']]],expected:[eq({'1':['a','b'],'2':['cc']})]}]},
'CP-L2-PY-003':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'paginate',adapter:'paginate',cases:[{id:'CP-L2-PY-003-hidden-1',calls:[[[1,2,3,4,5],1,2]],expected:[eq({kind:'return',value:[1,2]})]},{id:'CP-L2-PY-003-hidden-2',calls:[[[1,2,3,4,5],3,2]],expected:[eq({kind:'return',value:[5]})]},{id:'CP-L2-PY-003-hidden-3',calls:[[[1,2,3],5,2]],expected:[eq({kind:'return',value:[]})]},{id:'CP-L2-PY-003-hidden-4',calls:[[[1],0,2]],expected:[eq({kind:'throw',type:'ValueError'})]}]},correct:'def paginate(items,page,page_size):\n    if page<1 or page_size<1: raise ValueError("invalid page")\n    start=(page-1)*page_size\n    return items[start:start+page_size]',mutant:'def paginate(items,page,page_size):\n    if page<0 or page_size<0: raise ValueError()\n    return items[page*page_size:(page+1)*page_size]',developmentCases:[{id:'DEV-PY-PAGE-size-zero',calls:[[[1],1,0]],expected:[eq({kind:'throw',type:'ValueError'})]}]},
'CP-L2-TD-PY-004':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'Accumulator',adapter:'accumulator',cases:[{id:'CP-L2-TD-PY-004-hidden-1',calls:[['independent',1,2]],expected:[eq([1,2])]},{id:'CP-L2-TD-PY-004-hidden-2',calls:[['total',[3,4]]],expected:[eq(7)]}]},correct:'class Accumulator:\n    def __init__(self): self.items=[]\n    def add(self,x): self.items.append(x)\n    def total(self): return sum(self.items)',mutant:'class Accumulator:\n    items=[]\n    def add(self,x): self.items.append(x)\n    def total(self): return sum(self.items)',developmentCases:[{id:'DEV-PY-ACC-zero',calls:[['total',[]]],expected:[eq(0)]}]},
'CP-L3-AW-PY-001':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'apply_once',adapter:'apply-once',cases:[{id:'CP-L3-AW-PY-001-hidden-1',calls:[['repeat','x','r']],expected:[eq(['r','r',1])]},{id:'CP-L3-AW-PY-001-hidden-2',calls:[['two',1,2]],expected:[eq([1,2,{a:1,b:2}])]}]},correct:'def apply_once(action_id,store,fn):\n    if action_id in store: return store[action_id]\n    result=fn();store[action_id]=result;return result',mutant:'def apply_once(action_id,store,fn):\n    result=fn();store[action_id]=result;return result',developmentCases:[{id:'DEV-PY-ONCE-null',calls:[['repeat','x',null]],expected:[eq([null,null,1])]}]},
'CP-L3-AW-PY-002':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'topo_order',adapter:'topo-order',cases:[{id:'CP-L3-AW-PY-002-hidden-1',calls:[[{a:[],b:['a'],c:['b']}]],expected:[eq({kind:'return',valid:true})]},{id:'CP-L3-AW-PY-002-hidden-2',calls:[[{a:[],b:['a'],c:['a']}]],expected:[eq({kind:'return',valid:true})]},{id:'CP-L3-AW-PY-002-hidden-3',calls:[[{a:['b'],b:['a']}]],expected:[eq({kind:'throw',type:'ValueError',message:'cycle'})]}]},correct:'def topo_order(tasks):\n    state={};out=[]\n    def visit(n):\n        if state.get(n)==1: raise ValueError("cycle")\n        if state.get(n)==2: return\n        state[n]=1\n        for d in tasks.get(n,[]): visit(d)\n        state[n]=2;out.append(n)\n    for n in tasks: visit(n)\n    return out',mutant:'def topo_order(tasks):\n    return list(tasks)',developmentCases:[{id:'DEV-PY-TOPO-wide',calls:[[{a:[],b:['a'],c:['a'],d:['b','c']}]],expected:[eq({kind:'return',valid:true})]}]}}
