import type{IsolatedPythonJsonFixture}from'./isolatedPythonJsonGold.js';
import{ISOLATED_PYTHON_JSON_V3_PILOTS}from'./isolatedPythonJsonV3Gold.js';
const eq=(equals:any)=>({equals});
export const ISOLATED_PYTHON_JSON_V2_PILOTS:Record<string,IsolatedPythonJsonFixture>={...ISOLATED_PYTHON_JSON_V3_PILOTS,
'CP-L3-PERF-PY-001':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'has_pair_sum',adapter:'pair-sum',cases:[{id:'CP-L3-PERF-PY-001-hidden-1',calls:[[[1,2,3,9],5]],expected:[eq(true)]},{id:'CP-L3-PERF-PY-001-hidden-2',calls:[[[3],6]],expected:[eq(false)]},{id:'CP-L3-PERF-PY-001-hidden-3',calls:[[[1,2,3],6]],expected:[eq(false)]},{id:'CP-L3-PERF-PY-001-hidden-4',calls:[[[2,2],4]],expected:[eq(true)]},{id:'CP-L3-PERF-PY-001-hidden-5',calls:[['perf',300000,-1,1500]],expected:[eq([false,true])]}]},correct:'def has_pair_sum(nums,target):\n    seen=set()\n    for n in nums:\n        if target-n in seen:return True\n        seen.add(n)\n    return False',mutant:'def has_pair_sum(nums,target):\n    return any(target-n in nums for n in nums)',developmentCases:[{id:'DEV-PY-PAIR-neg',calls:[[[-3,1,7],4]],expected:[eq(true)]}]},
'CP-L3-PY-010':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'fetch_all',adapter:'fetch-all',cases:[{id:'CP-L3-PY-010-hidden-1',calls:[['values',['a','b','c','d','e']]],expected:[eq([['data:a','data:b','data:c','data:d','data:e'],5])]},{id:'CP-L3-PY-010-hidden-2',calls:[['empty']],expected:[eq([])]},{id:'CP-L3-PY-010-hidden-3',calls:[['error']],expected:[eq({kind:'throw',type:'ValueError'})]}]},correct:'import asyncio\nasync def fetch(url):\n    await asyncio.sleep(1);return f"data:{url}"\nasync def fetch_all(urls):\n    return await asyncio.gather(*(fetch(u) for u in urls))',mutant:'import asyncio\nasync def fetch(url):return "data:"+url\nasync def fetch_all(urls):\n    out=[]\n    for u in urls:out.append(await fetch(u))\n    return out',developmentCases:[{id:'DEV-PY-FETCH-two',calls:[['values',['x','y']]],expected:[eq([['data:x','data:y'],2])]}]},
'CP-L3-PY-012':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'histogram',adapter:'histogram',cases:[{id:'CP-L3-PY-012-hidden-1',calls:[[['a','b','a','c','b','a']]],expected:[eq([{a:3,b:2,c:1},true])]},{id:'CP-L3-PY-012-hidden-2',calls:[[[]]],expected:[eq([{},true])]},{id:'CP-L3-PY-012-hidden-3',calls:[[[1,2,1,2,3]]],expected:[eq([{'1':2,'2':2,'3':1},true])]}]},correct:'def histogram(items):\n    result={}\n    for item in items:result[item]=result.get(item,0)+1\n    return result',mutant:'def histogram(items):\n    result={}\n    while items:\n        x=items.pop();result[x]=result.get(x,0)+1\n    return result',developmentCases:[{id:'DEV-PY-HIST-one',calls:[[['z']]],expected:[eq([{z:1},true])]}]},
'CP-L3-SEC-PY-001':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'find_user',adapter:'sql-param',cases:[{id:'CP-L3-SEC-PY-001-hidden-1',calls:[['alice']],expected:[eq([[['alice']],"SELECT * FROM users WHERE name = ?",['alice']])]},{id:'CP-L3-SEC-PY-001-hidden-2',calls:[["x' OR '1'='1"]],expected:[eq([[],"SELECT * FROM users WHERE name = ?",["x' OR '1'='1"]])]}]},correct:'def find_user(conn,name):\n    cur=conn.cursor();cur.execute("SELECT * FROM users WHERE name = ?",(name,));return cur.fetchall()',mutant:'def find_user(conn,name):\n    cur=conn.cursor();cur.execute("SELECT * FROM users WHERE name = "+name);return cur.fetchall()',developmentCases:[{id:'DEV-PY-SQL-empty',calls:[['']],expected:[eq([[],"SELECT * FROM users WHERE name = ?",['']])]}]},
'CP-L3-SEC-PY-002':{language:'python',contract:{protocol:'isolated-python-json-v1',entrypoint:'read_upload',adapter:'path-safe',cases:[{id:'CP-L3-SEC-PY-002-hidden-1',calls:[['ok']],expected:[eq('hello')]},{id:'CP-L3-SEC-PY-002-hidden-2',calls:[['evil']],expected:[eq(['ValueError','ValueError','ValueError'])]}]},correct:'from pathlib import Path\ndef read_upload(base,name):\n    root=Path(base).resolve();path=(root/name).resolve()\n    if not path.is_relative_to(root):raise ValueError("outside base")\n    return path.read_text()',mutant:'import os\ndef read_upload(base,name):\n    with open(os.path.join(base,name)) as f:return f.read()',developmentCases:[{id:'DEV-PY-PATH-evil',calls:[['evil']],expected:[eq(['ValueError','ValueError','ValueError'])]}]}
};
