import type{IsolatedFixtureExitContract,FixtureLanguage}from'../execution/isolatedFixtureExit.js';
export interface IsolatedFixtureExitFixture{contract:IsolatedFixtureExitContract;correct:string;mutant:string}
const f=(entrypoint:string,language:FixtureLanguage,caseIds:string[],correct:string,mutant:string,mode:'cases'|'tsan'|'miri'='cases'):IsolatedFixtureExitFixture=>({contract:{protocol:'isolated-fixture-exit-v1',entrypoint,language,mode,caseIds},correct,mutant});
export const ISOLATED_FIXTURE_EXIT_PILOTS:Record<string,IsolatedFixtureExitFixture>={
'CP-L2-CC-001':f('join','c',['CP-L2-CC-001-hidden-1','CP-L2-CC-001-hidden-2'],'char *join(const char*a,const char*b){size_t n=strlen(a)+strlen(b)+1;char*d=malloc(n);if(!d)return NULL;memcpy(d,a,strlen(a));memcpy(d+strlen(a),b,strlen(b)+1);return d;}','char *join(const char*a,const char*b){char*d=malloc(strlen(a)+strlen(b));strcpy(d,a);strcat(d,b);return d;}'),
'CR2-CC-001':f('print_reverse','c',['CR2-CC-001-t1','CR2-CC-001-t2'],'#include <stddef.h>\nvoid print_reverse(const int*arr,size_t len){for(size_t i=len;i>0;--i)(void)arr[i-1];}','#include <stddef.h>\nvoid print_reverse(const int*arr,size_t len){for(size_t i=len-1;i>=0;i--)(void)arr[i];}'),
'CR2-CC-002':f('copy_name','c',['CR2-CC-002-t1'],'#include <string.h>\nvoid copy_name(char dest[16],const char*src){strncpy(dest,src,15);dest[15]=0;}','#include <string.h>\nvoid copy_name(char dest[16],const char*src){strcpy(dest,src);}'),
'CR2-CC-003':f('make_greeting','c',['CR2-CC-003-t1'],'#include <stdlib.h>\n#include <string.h>\nconst char*make_greeting(const char*name){size_t n=strlen(name)+8;char*b=malloc(n);if(!b)return NULL;strcpy(b,"Hello, ");strcat(b,name);return b;}','#include <string.h>\nconst char*make_greeting(const char*name){char b[128];strcpy(b,"Hello, ");strcat(b,name);return b;}'),
'CP-L3-CC-003':f('Builder','cpp',['CP-L3-CC-003-hidden-1','CP-L3-CC-003-hidden-2','CP-L3-CC-003-hidden-3','CP-L3-CC-003-hidden-4'],'#include <string>\n#include <utility>\n#include <vector>\nstruct Blob{std::string name;std::vector<int>data;};class Builder{std::vector<Blob>items_;public:void add(std::string name){Blob b;b.name=std::move(name);b.data.resize(1024);items_.push_back(std::move(b));}std::vector<Blob>build(){return std::move(items_);}};','#include <string>\n#include <vector>\nstruct Blob{std::string name;std::vector<int>data;};class Builder{std::vector<Blob>items_;public:void add(std::string n){Blob b;b.name=n;b.data.resize(1024);items_.push_back(b);}std::vector<Blob>build()const{return items_;}};'),
'CP-L3-CC-004':f('Device','cpp',['CP-L3-CC-004-hidden-1','CP-L3-CC-004-hidden-2','CP-L3-CC-004-hidden-3','CP-L3-CC-004-hidden-4'],'#include <iostream>\n#include <memory>\nstruct Device;struct Session:std::enable_shared_from_this<Session>{std::shared_ptr<Device>device;~Session(){std::cout<<"~Session\\n";}};struct Device{std::weak_ptr<Session>active;~Device(){std::cout<<"~Device\\n";}};void connect(){auto d=std::make_shared<Device>();auto s=std::make_shared<Session>();s->device=d;d->active=s;}','#include <iostream>\n#include <memory>\nstruct Device;struct Session:std::enable_shared_from_this<Session>{std::shared_ptr<Device>device;~Session(){std::cout<<"~Session\\n";}};struct Device{std::shared_ptr<Session>active;~Device(){std::cout<<"~Device\\n";}};void connect(){auto d=std::make_shared<Device>();auto s=std::make_shared<Session>();s->device=d;d->active=s;}'),
'CP-L3-CC-005':f('TreiberStack','cpp',['CP-L3-CC-005-tsan','CP-L3-CC-005-functional','CP-L3-CC-005-no-mutex'],'#include <atomic>\nclass TreiberStack{struct Node{int v;Node*next;};std::atomic<Node*>head_{nullptr};public:void push(int v){auto*n=new Node{v,nullptr};n->next=head_.load(std::memory_order_relaxed);while(!head_.compare_exchange_weak(n->next,n,std::memory_order_release,std::memory_order_relaxed)){}}bool pop(int&out){Node*h=head_.load(std::memory_order_acquire);while(h){if(head_.compare_exchange_weak(h,h->next,std::memory_order_acquire,std::memory_order_relaxed)){out=h->v;delete h;return true;}}return false;}};','#include <atomic>\nclass TreiberStack{struct Node{int v;Node*next;};std::atomic<Node*>head_{nullptr};public:void push(int v){auto*n=new Node{v,head_.load()};while(!head_.compare_exchange_weak(n->next,n,std::memory_order_release,std::memory_order_relaxed)){}}bool pop(int&out){Node*h=head_.load(std::memory_order_relaxed);while(h){if(head_.compare_exchange_weak(h,h->next,std::memory_order_relaxed)){out=h->v;delete h;return true;}}return false;}};','tsan'),
'CP-L2-RS-001':f('dedup_push','rust',['CP-L2-RS-001-hidden-1'],'fn dedup_push(v:&mut Vec<i32>,x:i32){if !v.contains(&x){v.push(x)}}','fn dedup_push(v:&mut Vec<i32>,x:i32){for &n in v.iter(){if n!=x{v.push(x)}}}'),
'CP-L3-RS-001':f('longest_line','rust',['CP-L3-RS-001-hidden-1','CP-L3-RS-001-hidden-2','CP-L3-RS-001-hidden-3','CP-L3-RS-001-hidden-4'],"fn longest_line<'a>(lines:&'a[&'a str])->&'a str{lines.iter().copied().max_by_key(|s|s.len()).unwrap_or(\"\")}","fn longest_line(lines:&[&str])->&'static str{lines.iter().max_by_key(|s|s.len()).map(|s|Box::leak(s.to_string().into_boxed_str())as&str).unwrap_or(\"\")}"),
'CP-L3-RS-002':f('Request','rust',['CP-L3-RS-002-hidden-1','CP-L3-RS-002-hidden-2','CP-L3-RS-002-hidden-3','CP-L3-RS-002-hidden-4','CP-L3-RS-002-hidden-5'],'pub struct Request{body:String,route_len:usize}impl Request{pub fn new(raw:String)->Self{let n=raw.find(" ").unwrap_or(raw.len());Self{body:raw,route_len:n}}pub fn route(&self)->&str{&self.body[..self.route_len]}}','pub struct Request{body:String,route_ptr:*const u8,route_len:usize}'),
'CP-L3-RS-003':f('split_two','rust',['rs003-miri-clean','rs003-split-boundary','rs003-oob-panic','rs003-no-transmute'],'pub fn split_two(buf:&mut[u8],mid:usize)->(&mut[u8],&mut[u8]){assert!(mid<=buf.len(),"mid out of range");buf.split_at_mut(mid)}','pub fn split_two(buf:&mut[u8],mid:usize)->(&mut[u8],&mut[u8]){let p=buf.as_mut_ptr();unsafe{(std::slice::from_raw_parts_mut(p,mid),std::slice::from_raw_parts_mut(p.add(mid),buf.len()-mid))}}pub fn reborrow_long<\'a,\'b:\'a>(x:&\'a mut u32)->&\'b mut u32{unsafe{std::mem::transmute(x)}}','miri'),
'CP-L3-JS-010':f('ImageCache','javascript',['CP-L3-JS-010-hidden-1','CP-L3-JS-010-hidden-2','CP-L3-JS-010-hidden-3','CP-L3-JS-010-hidden-4'],'class ImageCache{#map=new Map;#registry=new FinalizationRegistry(h=>{if(this.#map.get(h.key)?.token===h.token)this.#map.delete(h.key)});set(key,img){const old=this.#map.get(key);if(old)this.#registry.unregister(old.token);const token={};this.#map.set(key,{ref:new WeakRef(img),token});this.#registry.register(img,{key,token},token)}get(key){const e=this.#map.get(key),v=e?.ref.deref();if(e&&v===undefined)this.#map.delete(key);return v}purgeStale(){for(const[k,e]of this.#map)if(e.ref.deref()===undefined)this.#map.delete(k)}}','class ImageCache{#map=new Map;set(k,v){this.#map.set(k,v)}get(k){return this.#map.get(k)}}'),
'CP-L3-PY-013':f('OrderBook','python',['CP-L3-PY-013-hidden-1','CP-L3-PY-013-hidden-2','CP-L3-PY-013-hidden-3','CP-L3-PY-013-hidden-4'],'import threading\nfrom decimal import Decimal\nclass OrderBook:\n def __init__(self):self._bids=[];self._fills=[];self._next_id=1;self._lock=threading.RLock()\n def submit_bid(self,price,qty):\n  with self._lock:\n   oid=self._next_id;self._next_id+=1;self._bids.append((Decimal(str(price)),qty,oid));self._bids.sort(key=lambda b:(-b[0],b[2]));return oid\n def match(self,ask_price,ask_qty):\n  with self._lock:\n   ask=Decimal(str(ask_price));remaining=ask_qty;fills=[];new=[]\n   for price,qty,oid in self._bids:\n    if price<ask or remaining<=0:new.append((price,qty,oid));continue\n    take=min(qty,remaining);fill=(oid,price,take);fills.append(fill);self._fills.append(fill);remaining-=take\n    if qty>take:new.append((price,qty-take,oid))\n   self._bids=new;return fills','class OrderBook:\n def __init__(self):self._bids=[];self._fills=[];self._next_id=1\n def submit_bid(self,p,q):self._bids.append((float(p),q,self._next_id));self._next_id+=1;return self._next_id-1\n def match(self,p,q):return []'),
'CP-L3-SH-001':f('run_server','bash',['CP-L3-SH-001-hidden-1','CP-L3-SH-001-hidden-2','CP-L3-SH-001-hidden-3','CP-L3-SH-001-hidden-4'],`run_server(){ local LOG="\${SERVER_LOG:-/var/log/server.log}" TMPFILE child=""; TMPFILE=$(mktemp)||return; cleanup(){ [ -n "$child" ]&&kill "$child" 2>/dev/null||:; [ -n "$child" ]&&wait "$child" 2>/dev/null||:; rm -f -- "$TMPFILE"; }; trap 'cleanup' EXIT; trap 'cleanup; trap - EXIT; exit 0' INT TERM; set -o pipefail; while :;do echo "$(date): server is running"|tee -a "$LOG"||return 1; sleep 5& child=$!; wait "$child"||{ r=$?; [ "$r" -gt 128 ]&&return 0; return "$r"; };child="";done; }`,`run_server(){ local f;f=$(mktemp);trap "rm -f $f" EXIT;while :;do sleep 5&wait $!;done;}`),
'CP-L3-SH-002':f('top_ips','bash',['CP-L3-SH-002-hidden-1','CP-L3-SH-002-hidden-2','CP-L3-SH-002-hidden-3','CP-L3-SH-002-hidden-4'],`top_ips(){ awk '{print $1}' "$1"|sort|uniq -c|sort -k1,1nr -k2,2|head -10; }`,`top_ips(){ awk '{print $1}' "$1"|uniq -c|sort -nr|head;}`),
'CP-L3-SH-003':f('parse_csv_col2','bash',['CP-L3-SH-003-hidden-1','CP-L3-SH-003-hidden-2','CP-L3-SH-003-hidden-3','CP-L3-SH-003-hidden-4'],`parse_csv_col2(){ awk 'BEGIN{q=0;rec=""}{sub(/\\r$/,"");rec=(rec==""?$0:rec"\\n"$0);n=split($0,a,"");for(i=1;i<=n;i++)if(a[i]=="\\\""){if(q&&a[i+1]=="\\\"")i++;else q=!q}if(!q){field="";col=1;inq=0;n=length(rec);for(i=1;i<=n;i++){ch=substr(rec,i,1);nx=substr(rec,i+1,1);if(ch=="\\\""){if(inq&&nx=="\\\""){if(col==2)field=field"\\\"";i++}else inq=!inq}else if(ch==","&&!inq){col++}else if(col==2)field=field ch}print field;rec=""}}' "$1"; }`,`parse_csv_col2(){ while IFS=, read -r a b c;do echo "$b";done<"$1"; }`),
'CP-L3-SH-004':f('provision','bash',['CP-L3-SH-004-hidden-1','CP-L3-SH-004-hidden-2','CP-L3-SH-004-hidden-3','CP-L3-SH-004-hidden-4'],`provision(){ set -Eeuo pipefail; local DEST="\${DEST:-/opt/myapp}" SRC="\${SRC:-./assets}" cdest=0 cimg=0 cconf=0 clogo=0; rollback(){ local r=$?; echo "error at line $LINENO" >&2;[ "$clogo" = 1 ]&&rm -f "$DEST/images/logo.svg";[ "$cconf" = 1 ]&&rm -f "$DEST/app.conf";[ "$cimg" = 1 ]&&rmdir "$DEST/images" 2>/dev/null||:;[ "$cdest" = 1 ]&&rmdir "$DEST" 2>/dev/null||:;return "$r";};trap rollback ERR;[ -d "$DEST" ]||{ mkdir -p "$DEST";cdest=1;};[ -d "$DEST/images" ]||{ mkdir -p "$DEST/images";cimg=1;};if [ ! -f "$DEST/app.conf" ]||! cmp -s "$SRC/app.conf" "$DEST/app.conf";then [ -e "$DEST/app.conf" ]||cconf=1;cp "$SRC/app.conf" "$DEST/app.conf";fi;if [ ! -f "$DEST/images/logo.svg" ]||! cmp -s "$SRC/logo.svg" "$DEST/images/logo.svg";then [ -e "$DEST/images/logo.svg" ]||clogo=1;cp "$SRC/logo.svg" "$DEST/images/logo.svg";fi;trap - ERR;echo installed; }`,`provision(){ mkdir "$DEST";cp $SRC/app.conf $DEST/;}`),
'CP-L3-SH-005':f('sync_data','bash',['CP-L3-SH-005-hidden-1','CP-L3-SH-005-hidden-2','CP-L3-SH-005-hidden-3','CP-L3-SH-005-hidden-4'],`sync_data(){ local LOCK="\${LOCK:-/var/run/sync.lock}" DATA="\${DATA:-/srv/data.json}" URL="\${URL:-https://example.com/data.json}" tmp i;mkdir -p "$(dirname "$LOCK")" "$(dirname "$DATA")";exec 9>"$LOCK";flock -n 9||return 0;printf '%s\\n' "$$" 1>&9;tmp=$(mktemp "\${DATA}.tmp.XXXXXX")||return 1;trap 'rm -f -- "$tmp"' RETURN;for i in 1 2 3;do if curl -sf --max-time 30 "$URL" -o "$tmp";then mv -f "$tmp" "$DATA";trap - RETURN;return 0;fi;[ "$i" = 3 ]||sleep $((1<<(i-1)));done;return 1; }`,`sync_data(){ curl -sf "$URL" -o "$DATA.tmp";mv "$DATA.tmp" "$DATA";}`),
'CR2-SH-001':f('backup_file','bash',['CR2-SH-001-t1','CR2-SH-001-t2','CR2-SH-001-t3','CR2-SH-001-t4'],`backup_file(){ local src="$1" dest="$2";cp -- "$src" "$dest"&&chmod 644 "$dest"; }`,`backup_file(){ cp $1 $2;chmod 644 $2;}`),
'SH-001':f('increment_version','bash',['SH-001-hidden-1','SH-001-hidden-2','SH-001-hidden-3','SH-001-hidden-4','SH-001-hidden-5','SH-001-hidden-6'],`increment_version(){ local part="$1";echo $((10#$part+1)); }`,`increment_version(){ echo $(($1+1)); }`),
};
