import type{IsolatedGoJsonContract}from'../execution/isolatedGoJson.js';
export interface IsolatedGoJsonFixture{language:'go';contract:IsolatedGoJsonContract;correct:string;mutant:string;developmentCases:IsolatedGoJsonContract['cases']}
const eq=(equals:any)=>({equals});
export const ISOLATED_GO_JSON_PILOTS:Record<string,IsolatedGoJsonFixture>={
'CP-L3-GO-003':{language:'go',contract:{protocol:'isolated-go-json-v2',entrypoint:'FanIn',adapter:'fan-in',cases:[
  {id:'CP-L3-GO-003-hidden-1',calls:[[0,0,false,'values']],expected:[eq([])]},
  {id:'CP-L3-GO-003-hidden-2',calls:[[1,3,false,'values']],expected:[eq([0,1,2])]},
  {id:'CP-L3-GO-003-hidden-3',calls:[[1,2,true,'values']],expected:[eq([0,1])]},
  {id:'CP-L3-GO-003-hidden-4',calls:[[64,2048,false,'stats']],expected:[eq([131072,131072,8589869056])]}]},
  correct:'func FanIn(chans []<-chan int)<-chan int{out:=make(chan int);var wg sync.WaitGroup;for _,ch:=range chans{if ch==nil{continue};wg.Add(1);go func(c<-chan int){defer wg.Done();for v:=range c{out<-v}}(ch)};go func(){wg.Wait();close(out)}();return out}',
  mutant:'func FanIn(chans []<-chan int)<-chan int{out:=make(chan int);var wg sync.WaitGroup;for _,ch:=range chans{wg.Add(1);go func(c<-chan int){defer wg.Done();for v:=range c{out<-v}}(ch)};wg.Wait();close(out);return out}',developmentCases:[
    {id:'DEV-GO-FANIN-two',calls:[[2,4,false,'values']],expected:[eq([0,1,2,3,4,5,6,7])]},
    {id:'DEV-GO-FANIN-only-nil',calls:[[0,0,true,'values']],expected:[eq([])]}]},
'CP-L3-GO-004':{language:'go',contract:{protocol:'isolated-go-json-v2',entrypoint:'First',adapter:'first-http',cases:[
  {id:'CP-L3-GO-004-hidden-1',calls:[['fastest',1,500,0]],expected:[eq('fast')]},
  {id:'CP-L3-GO-004-hidden-2',calls:[['leak',200,0,0]],expected:[eq(true)]},
  {id:'CP-L3-GO-004-hidden-3',calls:[['allfail',1,0,0]],expected:[eq('')]},
  {id:'CP-L3-GO-004-hidden-4',calls:[['canceled',1,0,0]],expected:[eq(['',true])]}]},
  correct:'func First(ctx context.Context,urls ...string)string{ctx,cancel:=context.WithCancel(ctx);defer cancel();ch:=make(chan string,1);var wg sync.WaitGroup;for _,u:=range urls{wg.Add(1);go func(url string){defer wg.Done();req,err:=http.NewRequestWithContext(ctx,http.MethodGet,url,nil);if err!=nil{return};resp,err:=http.DefaultClient.Do(req);if err!=nil{return};defer resp.Body.Close();b,err:=io.ReadAll(resp.Body);if err!=nil{return};select{case ch<-string(b):case<-ctx.Done():}}(u)};done:=make(chan struct{});go func(){wg.Wait();close(done)}();select{case r:=<-ch:cancel();return r;case<-done:return "";case<-ctx.Done():return ""}}',
  mutant:'func First(ctx context.Context,urls ...string)string{ch:=make(chan string);ctx,cancel:=context.WithCancel(ctx);defer cancel();for _,u:=range urls{go func(u string){resp,err:=http.Get(u);if err!=nil{return};b,_:=io.ReadAll(resp.Body);resp.Body.Close();ch<-string(b)}(u)};select{case r:=<-ch:return r;case<-ctx.Done():return ""}}',developmentCases:[
    {id:'DEV-GO-FIRST-left-fast',calls:[['fastest',1,0,100]],expected:[eq('slow')]},
    {id:'DEV-GO-FIRST-leak-small',calls:[['leak',20,0,0]],expected:[eq(true)]}]},
'CP-L3-CONC-GO-001':{language:'go',contract:{protocol:'isolated-go-json-v2',entrypoint:'Counter.Inc',adapter:'race-counter',cases:[{id:'CP-L3-CONC-GO-001-hidden-1',calls:[[1,2]],expected:[eq(2)]},{id:'CP-L3-CONC-GO-001-hidden-2',calls:[[1000,1]],expected:[eq(1000)]}]},correct:'type Counter struct{mu sync.Mutex;n int}\nfunc(c *Counter)Inc(){c.mu.Lock();c.n++;c.mu.Unlock()}\nfunc(c *Counter)Get()int{c.mu.Lock();defer c.mu.Unlock();return c.n}',mutant:'type Counter struct{n int}\nfunc(c *Counter)Inc(){c.n++}\nfunc(c *Counter)Get()int{return c.n}',developmentCases:[{id:'DEV-GO-COUNTER-four',calls:[[4,25]],expected:[eq(100)]},{id:'DEV-GO-COUNTER-serial',calls:[[1,1]],expected:[eq(1)]}]},
'CP-L1-GO-001':{language:'go',contract:{protocol:'isolated-go-json-v1',entrypoint:'printAll',adapter:'goroutine-print',cases:[{id:'CP-L1-GO-001-hidden-1',calls:[[3]],expected:[eq([0,1,2])]},{id:'CP-L1-GO-001-hidden-2',calls:[[0]],expected:[eq([])]}]},correct:'func printAll(n int,out chan<- int){var wg sync.WaitGroup;for i:=0;i<n;i++{wg.Add(1);go func(v int){defer wg.Done();out<-v}(i)};wg.Wait();close(out)}',mutant:'func printAll(n int,out chan<- int){var wg sync.WaitGroup;for i:=0;i<n;i++{wg.Add(1);go func(){defer wg.Done();out<-i}()};wg.Wait();close(out)}',developmentCases:[{id:'DEV-GO-PRINT-one',calls:[[1]],expected:[eq([0])]},{id:'DEV-GO-PRINT-five',calls:[[5]],expected:[eq([0,1,2,3,4])]}]},
'CP-L2-GO-001':{language:'go',contract:{protocol:'isolated-go-json-v1',entrypoint:'CopyPrefix',adapter:'copy-prefix-alias',cases:[{id:'CP-L2-GO-001-hidden-1',calls:[[[1,2,3,4],2,'independent',99]],expected:[eq(true)]},{id:'CP-L2-GO-001-hidden-2',calls:[[[1,2,3],0,'length',0]],expected:[eq(0)]}]},correct:'func CopyPrefix(s []int,n int)[]int{r:=make([]int,n);copy(r,s[:n]);return r}',mutant:'func CopyPrefix(s []int,n int)[]int{return s[:n]}',developmentCases:[{id:'DEV-GO-COPY-full',calls:[[[4,5],2,'independent',9]],expected:[eq(true)]},{id:'DEV-GO-COPY-one',calls:[[[7,8],1,'length',0]],expected:[eq(1)]}]},
'CP-L2-GO-002':{language:'go',contract:{protocol:'isolated-go-json-v1',entrypoint:'Load',adapter:'error-wrap',cases:[{id:'CP-L2-GO-002-hidden-1',calls:[['missing']],expected:[eq(true)]}]},correct:'var ErrNotFound=errors.New("not found")\nfunc Load(id string)error{err:=fetch(id);if err!=nil{return fmt.Errorf("load %s failed: %w",id,err)};return nil}',mutant:'var ErrNotFound=errors.New("not found")\nfunc Load(id string)error{err:=fetch(id);if err!=nil{return fmt.Errorf("load %s failed",id)};return nil}',developmentCases:[{id:'DEV-GO-LOAD-present',calls:[['present']],expected:[eq(false)]},{id:'DEV-GO-LOAD-other',calls:[['x']],expected:[eq(false)]}]},
'CP-L2-TD-GO-001':{language:'go',contract:{protocol:'isolated-go-json-v1',entrypoint:'Atoi',adapter:'atoi-result',cases:[{id:'CP-L2-TD-GO-001-hidden-1',calls:[['123','value']],expected:[eq(123)]},{id:'CP-L2-TD-GO-001-hidden-2',calls:[['-45','value']],expected:[eq(-45)]},{id:'CP-L2-TD-GO-001-hidden-3',calls:[['1a2','hasError']],expected:[eq(true)]}]},correct:'func Atoi(s string)(int,error){if s==""{return 0,errors.New("invalid")};sign,i:=1,0;if s[0]==\'-\'{sign=-1;i=1};if i==len(s){return 0,errors.New("invalid")};n:=0;for ;i<len(s);i++{if s[i]<\'0\'||s[i]>\'9\'{return 0,errors.New("invalid")};n=n*10+int(s[i]-\'0\')};return sign*n,nil}',mutant:'func Atoi(s string)(int,error){n:=0;for _,c:=range s{n=n*10+int(c-\'0\')};return n,nil}',developmentCases:[{id:'DEV-GO-ATOI-zero',calls:[['0','value']],expected:[eq(0)]},{id:'DEV-GO-ATOI-empty',calls:[['','hasError']],expected:[eq(true)]}]}}
