import type{IsolatedSqlJsonContract}from'../execution/isolatedSqlJson.js';
export interface IsolatedSqlJsonFixture{language:'sql';contract:IsolatedSqlJsonContract;correct:string;mutant:string;developmentCases:IsolatedSqlJsonContract['cases']}
const eq=(equals:any)=>({equals});
const c=(id:string,schema:string,seed:string,expected:any,plan:Pick<IsolatedSqlJsonContract['cases'][number],'forbidPlan'|'requirePlan'>={})=>({id,schema,seed,expected:eq(expected),...plan});
const users='CREATE TABLE users(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE orders(id INTEGER PRIMARY KEY,user_id INTEGER,created_at TEXT,amount REAL,status TEXT);CREATE INDEX orders_user ON orders(user_id);';
const aggregateQuery="SELECT u.id,u.name,COUNT(o.id) FILTER(WHERE o.created_at>='2024-01-01') AS order_count_2024,SUM(o.amount) FILTER(WHERE o.status='completed') AS total_completed FROM users u JOIN orders o ON o.user_id=u.id GROUP BY u.id,u.name ORDER BY total_completed DESC NULLS LAST,u.id ASC LIMIT 100";
const aggregateSeed="INSERT INTO users VALUES(1,'A'),(2,'B'),(3,'C');INSERT INTO orders VALUES(1,1,'2024-02-01',10,'completed'),(2,1,'2023-01-01',20,'failed'),(3,2,'2024-03-01',5,'failed');";
const aggregateExpected=[{id:1,name:'A',order_count_2024:1,total_completed:10},{id:2,name:'B',order_count_2024:1,total_completed:null}];
const paymentSchema='CREATE TABLE payments(id INTEGER PRIMARY KEY,user_id INTEGER,created_at TEXT,amount REAL);CREATE INDEX payment_order ON payments(user_id,created_at,id);';
const paymentSeed="INSERT INTO payments VALUES(1,1,'2024-01-01 00:00:00',10),(2,1,'2024-01-01 00:00:00',20),(3,1,'2024-01-02',NULL),(4,2,'2024-01-01',5);";
const paymentExpected=[{user_id:1,created_at:'2024-01-01 00:00:00',amount:10,running_total:10},{user_id:1,created_at:'2024-01-01 00:00:00',amount:20,running_total:30},{user_id:1,created_at:'2024-01-02',amount:null,running_total:30},{user_id:2,created_at:'2024-01-01',amount:5,running_total:5}];
const paymentQuery='SELECT user_id,created_at,amount,SUM(COALESCE(amount,0)) OVER(PARTITION BY user_id ORDER BY created_at,id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM payments';
const employeeSchema='CREATE TABLE employees(id INTEGER PRIMARY KEY,manager_id INTEGER);';
const employeeSeed='INSERT INTO employees VALUES(1,2),(2,1),(3,1),(4,4),(5,99),(6,5),(10,NULL),(11,10),(12,11);';
const employeeQuery="WITH RECURSIVE up AS(SELECT id,manager_id,manager_id direct_mgr,0 depth,','||id||',' path,0 bad FROM employees UNION ALL SELECT up.id,e.manager_id,up.direct_mgr,up.depth+1,up.path||e.id||',',CASE WHEN instr(up.path,','||e.id||',')>0 THEN 1 ELSE 0 END FROM up JOIN employees e ON e.id=up.manager_id WHERE up.bad=0 AND up.depth<50) SELECT id,direct_mgr AS manager_id,CASE WHEN max(bad)=1 OR max(depth)>=50 THEN NULL ELSE max(depth) END AS depth FROM up GROUP BY id,direct_mgr ORDER BY id";
const employeeExpected=[{id:1,manager_id:2,depth:null},{id:2,manager_id:1,depth:null},{id:3,manager_id:1,depth:null},{id:4,manager_id:4,depth:null},{id:5,manager_id:99,depth:0},{id:6,manager_id:5,depth:1},{id:10,manager_id:null,depth:0},{id:11,manager_id:10,depth:1},{id:12,manager_id:11,depth:2}];
const eventSchema='CREATE TABLE events(id INTEGER PRIMARY KEY,created_at TEXT,level TEXT);CREATE INDEX events_created_at ON events(created_at);';
const eventSeed="INSERT INTO events VALUES(1,'2024-06-01 00:00:00','error'),(2,'2024-06-01 23:59:59.999','error'),(3,'2024-06-02 00:00:00','error'),(4,'2024-06-01 12:00:00','INFO');";
const eventExpected=[{id:2,created_at:'2024-06-01 23:59:59.999',level:'error'},{id:1,created_at:'2024-06-01 00:00:00',level:'error'}];
const eventQuery="SELECT * FROM events WHERE created_at>='2024-06-01' AND created_at<'2024-06-02' AND level='error' ORDER BY created_at DESC LIMIT 100";
export const ISOLATED_SQL_JSON_PILOTS:Record<string,IsolatedSqlJsonFixture>={
'CP-L2-SQL-001':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[c('CP-L2-SQL-001-hidden-1','CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,amount REAL);CREATE TABLE order_items(id INTEGER,order_id INTEGER);','INSERT INTO orders VALUES(1,1,100),(2,1,50),(3,2,40);INSERT INTO order_items VALUES(1,1),(2,1),(3,2),(4,3);',[{customer_id:1,total:150},{customer_id:2,total:40}]),c('CP-L2-SQL-001-hidden-2','CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,amount REAL);CREATE TABLE order_items(id INTEGER,order_id INTEGER);','INSERT INTO orders VALUES(1,1,0),(2,2,7);INSERT INTO order_items VALUES(1,1);',[{customer_id:1,total:0},{customer_id:2,total:7}])]},correct:'SELECT customer_id,SUM(amount) AS total FROM orders GROUP BY customer_id ORDER BY customer_id',mutant:'SELECT o.customer_id,SUM(o.amount) total FROM orders o JOIN order_items i ON i.order_id=o.id GROUP BY o.customer_id ORDER BY o.customer_id',developmentCases:[c('DEV-SQL-FANOUT','CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,amount REAL);CREATE TABLE order_items(id INTEGER,order_id INTEGER);','INSERT INTO orders VALUES(1,9,3);INSERT INTO order_items VALUES(1,1),(2,1),(3,1);',[{customer_id:9,total:3}])]},
'CP-L3-PERF-SQL-001':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[c('CP-L3-PERF-SQL-001-hidden-1',users,"INSERT INTO users VALUES(1,'A'),(2,'B');INSERT INTO orders VALUES(1,1,'2024-01-01',1,'completed'),(2,1,'2024-02-01',1,'completed');",[{user_id:1,last_order:'2024-02-01'},{user_id:2,last_order:null}],{forbidPlan:['CORRELATED SCALAR SUBQUERY']}),c('CP-L3-PERF-SQL-001-hidden-2',users,"INSERT INTO users VALUES(1,'A');",[{user_id:1,last_order:null}],{forbidPlan:['CORRELATED SCALAR SUBQUERY']})]},correct:'SELECT u.id AS user_id,MAX(o.created_at) AS last_order FROM users u LEFT JOIN orders o ON o.user_id=u.id GROUP BY u.id ORDER BY u.id',mutant:'SELECT u.id user_id,(SELECT MAX(o.created_at) FROM orders o WHERE o.user_id=u.id) last_order FROM users u ORDER BY u.id',developmentCases:[c('DEV-SQL-LAST',users,"INSERT INTO users VALUES(7,'X');INSERT INTO orders VALUES(1,7,'2020-01-01',1,'x');",[{user_id:7,last_order:'2020-01-01'}],{forbidPlan:['CORRELATED SCALAR SUBQUERY']})]},
'CP-L3-SQL-003':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[1,2,3,4].map(n=>c(`CP-L3-SQL-003-hidden-${n}`,users,aggregateSeed,aggregateExpected,{forbidPlan:['CORRELATED SCALAR SUBQUERY']}))},correct:aggregateQuery,mutant:'SELECT u.id,u.name,(SELECT COUNT(*) FROM orders o WHERE o.user_id=u.id) order_count_2024,(SELECT SUM(amount) FROM orders o WHERE o.user_id=u.id) total_completed FROM users u',developmentCases:[c('DEV-SQL-AGG',users,aggregateSeed,aggregateExpected,{forbidPlan:['CORRELATED SCALAR SUBQUERY']})]},
'CP-L3-SQL-004':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[1,2,3,4].map(n=>c(`CP-L3-SQL-004-hidden-${n}`,paymentSchema,paymentSeed,paymentExpected))},correct:paymentQuery,mutant:'SELECT user_id,created_at,amount,SUM(amount) OVER(PARTITION BY user_id ORDER BY created_at) running_total FROM payments',developmentCases:[c('DEV-SQL-WINDOW',paymentSchema,paymentSeed,paymentExpected)]},
'CP-L3-SQL-005':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[1,2,3,4,5].map(n=>c(`CP-L3-SQL-005-hidden-${n}`,employeeSchema,employeeSeed,employeeExpected))},correct:employeeQuery,mutant:'WITH RECURSIVE up AS(SELECT id,manager_id,0 depth FROM employees UNION ALL SELECT up.id,e.manager_id,up.depth+1 FROM up JOIN employees e ON e.id=up.manager_id) SELECT id,manager_id,max(depth) depth FROM up GROUP BY id,manager_id',developmentCases:[c('DEV-SQL-CYCLE',employeeSchema,employeeSeed,employeeExpected)]},
'CP-L3-SQL-006':{language:'sql',contract:{protocol:'isolated-sql-json-v1',entrypoint:'query',cases:[1,2,3,4].map(n=>c(`CP-L3-SQL-006-hidden-${n}`,eventSchema,eventSeed,eventExpected,n===1?{requirePlan:['SEARCH events']}:{ }))},correct:eventQuery,mutant:"SELECT * FROM events WHERE DATE(created_at)='2024-06-01' AND UPPER(level)='ERROR' ORDER BY created_at DESC LIMIT 100",developmentCases:[c('DEV-SQL-RANGE',eventSchema,eventSeed,eventExpected,{requirePlan:['SEARCH events']})]}
};
